-- ============================================================
-- Validate Setup — Run after deployment to confirm everything works
-- ============================================================
USE DATABASE ON_GOVERNANCE_RFS;

-- 1. Check table row counts
SELECT 'Tables' AS CHECK_TYPE;
SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA NOT IN ('PUBLIC', 'INFORMATION_SCHEMA')
ORDER BY TABLE_SCHEMA;

-- 2. Check tags are applied
SELECT 'Tags' AS CHECK_TYPE;
SELECT
  OBJECT_NAME,
  TAG_NAME,
  TAG_VALUE
FROM TABLE(INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
  'ON_GOVERNANCE_RFS.MCCSS.CLIENT_RETENTION_METRICS', 'TABLE'
))
WHERE LEVEL = 'TABLE';

-- 3. Check DMFs attached
SELECT 'DMFs' AS CHECK_TYPE;
SELECT METRIC_NAME, REF_ENTITY_NAME, REF_COLUMN_NAME
FROM TABLE(INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'ON_GOVERNANCE_RFS.MOH.ER_WAIT_TIME_ANALYTICS',
  REF_ENTITY_DOMAIN => 'TABLE'
));

-- 4. Check roles exist
SELECT 'Roles' AS CHECK_TYPE;
SHOW ROLES LIKE 'OPS_%';

-- 5. Check grants
SELECT 'Grants' AS CHECK_TYPE;
SHOW GRANTS TO ROLE OPS_DATA_ANALYST;

-- 6. Check masking policy
SELECT 'Masking' AS CHECK_TYPE;
SHOW MASKING POLICIES IN DATABASE ON_GOVERNANCE_RFS;

-- 7. Check Cortex Search service
SELECT 'Cortex Search' AS CHECK_TYPE;
SHOW CORTEX SEARCH SERVICES IN DATABASE ON_GOVERNANCE_RFS;

-- 8. Check stored procedures
SELECT 'Procedures' AS CHECK_TYPE;
SHOW PROCEDURES IN DATABASE ON_GOVERNANCE_RFS;

-- 9. Check access requests pre-seeded
SELECT 'Access Requests' AS CHECK_TYPE;
SELECT STATUS, COUNT(*) AS CNT FROM PUBLIC.ACCESS_REQUESTS GROUP BY STATUS;

-- 10. Verify masking works (query as restricted role)
SELECT 'Masking Test' AS CHECK_TYPE;
USE ROLE OPS_GENERAL_USER;
SELECT CLIENT_ID, POSTAL_CODE_PREFIX FROM MCCSS.CUSTOMER_DEMOGRAPHICS LIMIT 3;
-- Should show ***MASKED*** for both columns

USE ROLE ACCOUNTADMIN;
SELECT CLIENT_ID, POSTAL_CODE_PREFIX FROM MCCSS.CUSTOMER_DEMOGRAPHICS LIMIT 3;
-- Should show actual values
