-- ============================================================
-- 05: Apply Tags to All Tables and Columns
-- ============================================================
USE DATABASE ON_GOVERNANCE_RFS;

-- ============================================================
-- TABLE-LEVEL TAGS
-- ============================================================

-- MCCSS.CLIENT_RETENTION_METRICS (Story 1 - Authoritative, AI-Ready)
ALTER TABLE MCCSS.CLIENT_RETENTION_METRICS SET TAG
  PUBLIC.CERTIFICATION = 'Authoritative',
  PUBLIC.SENSITIVITY = 'INTERNAL',
  PUBLIC.AI_READY = 'TRUE',
  PUBLIC.ML_ENABLED = 'FALSE',
  PUBLIC.DATA_OWNER = 'Sarah Chen',
  PUBLIC.DATA_STEWARD = 'Michael Torres',
  PUBLIC.DOMAIN = 'MCCSS',
  PUBLIC.QUALITY_STATUS = 'HEALTHY',
  PUBLIC.DELIVERY_METHOD = 'TABLE';

-- MCCSS.CUSTOMER_DEMOGRAPHICS (Story 1 - AI-Ready, basket item)
ALTER TABLE MCCSS.CUSTOMER_DEMOGRAPHICS SET TAG
  PUBLIC.CERTIFICATION = 'Certified',
  PUBLIC.SENSITIVITY = 'RESTRICTED',
  PUBLIC.AI_READY = 'TRUE',
  PUBLIC.ML_ENABLED = 'FALSE',
  PUBLIC.DATA_OWNER = 'Sarah Chen',
  PUBLIC.DATA_STEWARD = 'Michael Torres',
  PUBLIC.DOMAIN = 'MCCSS',
  PUBLIC.QUALITY_STATUS = 'HEALTHY',
  PUBLIC.DELIVERY_METHOD = 'TABLE';

-- FIN.BUSINESS_ENTITY_REVENUE_TRANSACTIONS (Story 2 - Restricted)
ALTER TABLE FIN.BUSINESS_ENTITY_REVENUE_TRANSACTIONS SET TAG
  PUBLIC.CERTIFICATION = 'Authoritative',
  PUBLIC.SENSITIVITY = 'RESTRICTED',
  PUBLIC.AI_READY = 'FALSE',
  PUBLIC.ML_ENABLED = 'FALSE',
  PUBLIC.DATA_OWNER = 'David Park',
  PUBLIC.DATA_STEWARD = 'Angela Rossi',
  PUBLIC.DOMAIN = 'FIN',
  PUBLIC.QUALITY_STATUS = 'HEALTHY',
  PUBLIC.DELIVERY_METHOD = 'VIEW';

-- MOH.ER_WAIT_TIME_ANALYTICS (Story 3 - Publish candidate)
ALTER TABLE MOH.ER_WAIT_TIME_ANALYTICS SET TAG
  PUBLIC.CERTIFICATION = 'Authoritative',
  PUBLIC.SENSITIVITY = 'INTERNAL',
  PUBLIC.AI_READY = 'FALSE',
  PUBLIC.ML_ENABLED = 'FALSE',
  PUBLIC.DATA_OWNER = 'Dr. Rajesh Patel',
  PUBLIC.DATA_STEWARD = 'Emily Watson',
  PUBLIC.DOMAIN = 'MOH',
  PUBLIC.QUALITY_STATUS = 'HEALTHY',
  PUBLIC.DELIVERY_METHOD = 'TABLE';

-- MOH.PATIENT_OUTCOME_FEATURES (Story 4 - AI-Ready, ML-Enabled)
ALTER TABLE MOH.PATIENT_OUTCOME_FEATURES SET TAG
  PUBLIC.CERTIFICATION = 'Authoritative',
  PUBLIC.SENSITIVITY = 'RESTRICTED',
  PUBLIC.AI_READY = 'TRUE',
  PUBLIC.ML_ENABLED = 'TRUE',
  PUBLIC.DATA_OWNER = 'Dr. Rajesh Patel',
  PUBLIC.DATA_STEWARD = 'Emily Watson',
  PUBLIC.DOMAIN = 'MOH',
  PUBLIC.QUALITY_STATUS = 'HEALTHY',
  PUBLIC.DELIVERY_METHOD = 'FEATURE_TABLE';

-- EDU.STUDENT_ACHIEVEMENT_INDICATORS (Classification demo)
ALTER TABLE EDU.STUDENT_ACHIEVEMENT_INDICATORS SET TAG
  PUBLIC.CERTIFICATION = 'Draft',
  PUBLIC.SENSITIVITY = 'INTERNAL',
  PUBLIC.AI_READY = 'FALSE',
  PUBLIC.ML_ENABLED = 'FALSE',
  PUBLIC.DATA_OWNER = 'Jennifer Wu',
  PUBLIC.DATA_STEWARD = 'Robert Okafor',
  PUBLIC.DOMAIN = 'EDU',
  PUBLIC.QUALITY_STATUS = 'WARNING',
  PUBLIC.DELIVERY_METHOD = 'TABLE';

-- MTO.ROAD_INFRASTRUCTURE_METRICS (Cross-domain)
ALTER TABLE MTO.ROAD_INFRASTRUCTURE_METRICS SET TAG
  PUBLIC.CERTIFICATION = 'Certified',
  PUBLIC.SENSITIVITY = 'PUBLIC',
  PUBLIC.AI_READY = 'FALSE',
  PUBLIC.ML_ENABLED = 'FALSE',
  PUBLIC.DATA_OWNER = 'Mark Thompson',
  PUBLIC.DATA_STEWARD = 'Lisa Nguyen',
  PUBLIC.DOMAIN = 'MTO',
  PUBLIC.QUALITY_STATUS = 'HEALTHY',
  PUBLIC.DELIVERY_METHOD = 'TABLE';

-- ENERGY.ENERGY_GRID_TELEMETRY (Cross-domain)
ALTER TABLE ENERGY.ENERGY_GRID_TELEMETRY SET TAG
  PUBLIC.CERTIFICATION = 'Certified',
  PUBLIC.SENSITIVITY = 'PUBLIC',
  PUBLIC.AI_READY = 'TRUE',
  PUBLIC.ML_ENABLED = 'FALSE',
  PUBLIC.DATA_OWNER = 'Priya Sharma',
  PUBLIC.DATA_STEWARD = 'James Liu',
  PUBLIC.DOMAIN = 'ENERGY',
  PUBLIC.QUALITY_STATUS = 'HEALTHY',
  PUBLIC.DELIVERY_METHOD = 'API';

-- LABOUR.WORKFORCE_DEVELOPMENT_FEATURES (Story 4 - AI)
ALTER TABLE LABOUR.WORKFORCE_DEVELOPMENT_FEATURES SET TAG
  PUBLIC.CERTIFICATION = 'Certified',
  PUBLIC.SENSITIVITY = 'INTERNAL',
  PUBLIC.AI_READY = 'TRUE',
  PUBLIC.ML_ENABLED = 'TRUE',
  PUBLIC.DATA_OWNER = 'Karen Fletcher',
  PUBLIC.DATA_STEWARD = 'Ahmed Hassan',
  PUBLIC.DOMAIN = 'LABOUR',
  PUBLIC.QUALITY_STATUS = 'HEALTHY',
  PUBLIC.DELIVERY_METHOD = 'FEATURE_TABLE';

-- ============================================================
-- COLUMN-LEVEL SENSITIVITY TAGS (for masking demonstration)
-- ============================================================
-- These columns will be masked for unauthorized roles

-- MCCSS Demographics - PII columns
ALTER TABLE MCCSS.CUSTOMER_DEMOGRAPHICS MODIFY COLUMN
  CLIENT_ID SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';
ALTER TABLE MCCSS.CUSTOMER_DEMOGRAPHICS MODIFY COLUMN
  POSTAL_CODE_PREFIX SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';
ALTER TABLE MCCSS.CUSTOMER_DEMOGRAPHICS MODIFY COLUMN
  INDIGENOUS_IDENTITY SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';
ALTER TABLE MCCSS.CUSTOMER_DEMOGRAPHICS MODIFY COLUMN
  DISABILITY_FLAG SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';

-- FIN Revenue - Confidential financial columns
ALTER TABLE FIN.BUSINESS_ENTITY_REVENUE_TRANSACTIONS MODIFY COLUMN
  ENTITY_NAME SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';
ALTER TABLE FIN.BUSINESS_ENTITY_REVENUE_TRANSACTIONS MODIFY COLUMN
  BN_NUMBER SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';
ALTER TABLE FIN.BUSINESS_ENTITY_REVENUE_TRANSACTIONS MODIFY COLUMN
  REVENUE_AMOUNT SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';
ALTER TABLE FIN.BUSINESS_ENTITY_REVENUE_TRANSACTIONS MODIFY COLUMN
  TAX_COLLECTED SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';

-- MOH Patient Features - Health PII
ALTER TABLE MOH.PATIENT_OUTCOME_FEATURES MODIFY COLUMN
  PATIENT_ID SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';
ALTER TABLE MOH.PATIENT_OUTCOME_FEATURES MODIFY COLUMN
  HBA1C SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';

-- EDU Student - Student PII
ALTER TABLE EDU.STUDENT_ACHIEVEMENT_INDICATORS MODIFY COLUMN
  STUDENT_ID SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';
ALTER TABLE EDU.STUDENT_ACHIEVEMENT_INDICATORS MODIFY COLUMN
  POSTAL_CODE SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';

-- MOH ER - Patient identifiers
ALTER TABLE MOH.ER_WAIT_TIME_ANALYTICS MODIFY COLUMN
  PATIENT_ID SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';
ALTER TABLE MOH.ER_WAIT_TIME_ANALYTICS MODIFY COLUMN
  PHYSICIAN_ID SET TAG PUBLIC.SENSITIVITY = 'RESTRICTED';
