-- ============================================================
-- 06: Roles and Grants
-- ============================================================
USE ROLE ACCOUNTADMIN;

-- ============================================================
-- CREATE DEMO ROLES
-- ============================================================
CREATE ROLE IF NOT EXISTS OPS_DATA_OWNER
  COMMENT = 'Data product owner — full access, publish, classify, approve requests';
CREATE ROLE IF NOT EXISTS OPS_DATA_STEWARD
  COMMENT = 'Data steward — review classifications, manage quality, oversee governance';
CREATE ROLE IF NOT EXISTS OPS_CONTRIBUTOR
  COMMENT = 'Data contributor — prepare, validate, submit datasets for publication';
CREATE ROLE IF NOT EXISTS OPS_DATA_ANALYST
  COMMENT = 'Data analyst — full access to Certified/Authoritative data products';
CREATE ROLE IF NOT EXISTS OPS_DATA_SCIENTIST
  COMMENT = 'Data scientist — AI-Ready datasets, API delivery, feature tables';
CREATE ROLE IF NOT EXISTS OPS_GENERAL_USER
  COMMENT = 'General user — PUBLIC data only, must request INTERNAL/RESTRICTED';

-- ============================================================
-- ROLE HIERARCHY
-- ============================================================
GRANT ROLE OPS_GENERAL_USER TO ROLE OPS_DATA_ANALYST;
GRANT ROLE OPS_DATA_ANALYST TO ROLE OPS_DATA_SCIENTIST;
GRANT ROLE OPS_DATA_SCIENTIST TO ROLE OPS_CONTRIBUTOR;
GRANT ROLE OPS_CONTRIBUTOR TO ROLE OPS_DATA_STEWARD;
GRANT ROLE OPS_DATA_STEWARD TO ROLE OPS_DATA_OWNER;
GRANT ROLE OPS_DATA_OWNER TO ROLE ACCOUNTADMIN;

-- Grant roles to current user for demo
GRANT ROLE OPS_DATA_OWNER TO USER MBIJELIC;
GRANT ROLE OPS_DATA_STEWARD TO USER MBIJELIC;
GRANT ROLE OPS_CONTRIBUTOR TO USER MBIJELIC;
GRANT ROLE OPS_DATA_ANALYST TO USER MBIJELIC;
GRANT ROLE OPS_DATA_SCIENTIST TO USER MBIJELIC;
GRANT ROLE OPS_GENERAL_USER TO USER MBIJELIC;

-- ============================================================
-- DATABASE & SCHEMA GRANTS
-- ============================================================
GRANT USAGE ON DATABASE ON_GOVERNANCE_RFS TO ROLE OPS_GENERAL_USER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ON_GOVERNANCE_RFS TO ROLE OPS_GENERAL_USER;

-- Warehouse
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE OPS_GENERAL_USER;

-- ============================================================
-- TABLE GRANTS BY ROLE
-- ============================================================

-- OPS_GENERAL_USER: PUBLIC tables only
GRANT SELECT ON TABLE ON_GOVERNANCE_RFS.MTO.ROAD_INFRASTRUCTURE_METRICS TO ROLE OPS_GENERAL_USER;
GRANT SELECT ON TABLE ON_GOVERNANCE_RFS.ENERGY.ENERGY_GRID_TELEMETRY TO ROLE OPS_GENERAL_USER;

-- OPS_DATA_ANALYST: All INTERNAL + PUBLIC tables
GRANT SELECT ON TABLE ON_GOVERNANCE_RFS.MCCSS.CLIENT_RETENTION_METRICS TO ROLE OPS_DATA_ANALYST;
GRANT SELECT ON TABLE ON_GOVERNANCE_RFS.MOH.ER_WAIT_TIME_ANALYTICS TO ROLE OPS_DATA_ANALYST;
GRANT SELECT ON TABLE ON_GOVERNANCE_RFS.EDU.STUDENT_ACHIEVEMENT_INDICATORS TO ROLE OPS_DATA_ANALYST;
GRANT SELECT ON TABLE ON_GOVERNANCE_RFS.LABOUR.WORKFORCE_DEVELOPMENT_FEATURES TO ROLE OPS_DATA_ANALYST;

-- OPS_DATA_SCIENTIST: AI-Ready + RESTRICTED (masked)
GRANT SELECT ON TABLE ON_GOVERNANCE_RFS.MCCSS.CUSTOMER_DEMOGRAPHICS TO ROLE OPS_DATA_SCIENTIST;
GRANT SELECT ON TABLE ON_GOVERNANCE_RFS.MOH.PATIENT_OUTCOME_FEATURES TO ROLE OPS_DATA_SCIENTIST;

-- OPS_CONTRIBUTOR: Same as Data Scientist + write to publish staging
GRANT SELECT ON ALL TABLES IN DATABASE ON_GOVERNANCE_RFS TO ROLE OPS_CONTRIBUTOR;

-- OPS_DATA_STEWARD: Full read + governance tables
GRANT SELECT ON ALL TABLES IN DATABASE ON_GOVERNANCE_RFS TO ROLE OPS_DATA_STEWARD;
GRANT INSERT, UPDATE ON TABLE ON_GOVERNANCE_RFS.PUBLIC.ACCESS_REQUESTS TO ROLE OPS_DATA_STEWARD;
GRANT INSERT ON TABLE ON_GOVERNANCE_RFS.PUBLIC.CLASSIFICATION_AUDIT TO ROLE OPS_DATA_STEWARD;

-- OPS_DATA_OWNER: Full access including RESTRICTED unmasked
GRANT ALL ON ALL TABLES IN DATABASE ON_GOVERNANCE_RFS TO ROLE OPS_DATA_OWNER;
GRANT ALL ON ALL SCHEMAS IN DATABASE ON_GOVERNANCE_RFS TO ROLE OPS_DATA_OWNER;

-- FIN Revenue Transactions: NOT granted to General User (Story 2)
-- Access must be requested and approved

-- ============================================================
-- FUTURE GRANTS (for new objects)
-- ============================================================
GRANT SELECT ON FUTURE TABLES IN DATABASE ON_GOVERNANCE_RFS TO ROLE OPS_DATA_OWNER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ON_GOVERNANCE_RFS TO ROLE OPS_DATA_OWNER;
