-- ============================================================
-- 07: Data Metric Functions (DMFs) and Quality Monitoring
-- ============================================================
USE DATABASE ON_GOVERNANCE_RFS;
USE SCHEMA PUBLIC;

-- ============================================================
-- CUSTOM DMFs
-- ============================================================

-- Freshness: hours since most recent record
CREATE OR REPLACE DATA METRIC FUNCTION FRESHNESS_HOURS(
  ARG_T TABLE(LAST_UPDATED TIMESTAMP_NTZ)
)
RETURNS NUMBER
COMMENT = 'Returns hours since the most recent record was loaded'
AS
$$
  SELECT COALESCE(DATEDIFF(hour, MAX(LAST_UPDATED), CURRENT_TIMESTAMP()), -1) FROM ARG_T
$$;

-- Completeness: percentage of non-null values
CREATE OR REPLACE DATA METRIC FUNCTION COMPLETENESS_PCT(
  ARG_T TABLE(COL VARCHAR)
)
RETURNS NUMBER
COMMENT = 'Returns percentage of non-null values (0-100)'
AS
$$
  SELECT ROUND(COUNT(COL) * 100.0 / NULLIF(COUNT(*), 0), 1) FROM ARG_T
$$;

-- Out of range count for numeric validation
CREATE OR REPLACE DATA METRIC FUNCTION OUT_OF_RANGE_COUNT(
  ARG_T TABLE(COL NUMBER)
)
RETURNS NUMBER
COMMENT = 'Returns count of values outside expected range (negative values)'
AS
$$
  SELECT COUNT(*) FROM ARG_T WHERE COL < 0
$$;

-- ============================================================
-- ATTACH SYSTEM DMFs TO PRIMARY KEYS
-- ============================================================

-- MCCSS: Client Retention
ALTER TABLE MCCSS.CLIENT_RETENTION_METRICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CLIENT_ID);
ALTER TABLE MCCSS.CLIENT_RETENTION_METRICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CLIENT_ID);

-- MCCSS: Customer Demographics
ALTER TABLE MCCSS.CUSTOMER_DEMOGRAPHICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CLIENT_ID);
ALTER TABLE MCCSS.CUSTOMER_DEMOGRAPHICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CLIENT_ID);

-- FIN: Revenue Transactions
ALTER TABLE FIN.BUSINESS_ENTITY_REVENUE_TRANSACTIONS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (TRANSACTION_ID);
ALTER TABLE FIN.BUSINESS_ENTITY_REVENUE_TRANSACTIONS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (TRANSACTION_ID);

-- MOH: ER Wait Times
ALTER TABLE MOH.ER_WAIT_TIME_ANALYTICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (VISIT_ID);
ALTER TABLE MOH.ER_WAIT_TIME_ANALYTICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (VISIT_ID);

-- MOH: Patient Outcome Features
ALTER TABLE MOH.PATIENT_OUTCOME_FEATURES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PATIENT_ID);
ALTER TABLE MOH.PATIENT_OUTCOME_FEATURES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (PATIENT_ID);

-- EDU: Student Achievement
ALTER TABLE EDU.STUDENT_ACHIEVEMENT_INDICATORS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (STUDENT_ID);
ALTER TABLE EDU.STUDENT_ACHIEVEMENT_INDICATORS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (STUDENT_ID);

-- MTO: Road Infrastructure
ALTER TABLE MTO.ROAD_INFRASTRUCTURE_METRICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (SEGMENT_ID);

-- ENERGY: Grid Telemetry
ALTER TABLE ENERGY.ENERGY_GRID_TELEMETRY
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (READING_ID);

-- LABOUR: Workforce Features
ALTER TABLE LABOUR.WORKFORCE_DEVELOPMENT_FEATURES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PARTICIPANT_ID);
ALTER TABLE LABOUR.WORKFORCE_DEVELOPMENT_FEATURES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (PARTICIPANT_ID);

-- ============================================================
-- ATTACH CUSTOM DMFs
-- ============================================================

ALTER TABLE MCCSS.CLIENT_RETENTION_METRICS
  ADD DATA METRIC FUNCTION FRESHNESS_HOURS ON (LAST_UPDATED);
ALTER TABLE MOH.ER_WAIT_TIME_ANALYTICS
  ADD DATA METRIC FUNCTION FRESHNESS_HOURS ON (LAST_UPDATED);
ALTER TABLE MOH.PATIENT_OUTCOME_FEATURES
  ADD DATA METRIC FUNCTION FRESHNESS_HOURS ON (LAST_UPDATED);

-- ============================================================
-- DMF SCHEDULE
-- ============================================================
ALTER DATABASE ON_GOVERNANCE_RFS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

-- ============================================================
-- QUALITY ALERT
-- ============================================================
CREATE OR REPLACE ALERT QUALITY_ALERT
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 7 * * * America/Toronto'
  IF (EXISTS (
    SELECT 1
    FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
    WHERE TABLE_DATABASE = 'ON_GOVERNANCE_RFS'
      AND METRIC_NAME = 'NULL_COUNT'
      AND VALUE > 100
      AND MEASUREMENT_TIME > DATEADD(hour, -25, CURRENT_TIMESTAMP())
  ))
  THEN
    CALL SYSTEM$SEND_EMAIL(
      'ops_governance_notifications',
      'data-stewards@ontario.ca',
      'OPS Data Quality Alert: High Null Count Detected',
      'One or more governed tables in ON_GOVERNANCE_RFS have exceeded the null count threshold. Review the Governance Console.'
    );

ALTER ALERT QUALITY_ALERT RESUME;

-- ============================================================
-- QUALITY SCORECARD VIEW
-- ============================================================
CREATE OR REPLACE VIEW QUALITY_SCORECARD AS
SELECT
  TABLE_SCHEMA,
  TABLE_NAME,
  MAX(CASE WHEN METRIC_NAME = 'NULL_COUNT' THEN VALUE END) AS NULL_COUNT,
  MAX(CASE WHEN METRIC_NAME = 'DUPLICATE_COUNT' THEN VALUE END) AS DUPLICATE_COUNT,
  MAX(CASE WHEN METRIC_NAME = 'FRESHNESS_HOURS' THEN VALUE END) AS FRESHNESS_HOURS,
  MAX(MEASUREMENT_TIME) AS LAST_MEASURED,
  CASE
    WHEN MAX(CASE WHEN METRIC_NAME = 'NULL_COUNT' THEN VALUE END) = 0
     AND COALESCE(MAX(CASE WHEN METRIC_NAME = 'DUPLICATE_COUNT' THEN VALUE END), 0) = 0
    THEN 'HEALTHY'
    WHEN MAX(CASE WHEN METRIC_NAME = 'NULL_COUNT' THEN VALUE END) > 100
    THEN 'CRITICAL'
    WHEN MAX(CASE WHEN METRIC_NAME = 'NULL_COUNT' THEN VALUE END) > 10
    THEN 'WARNING'
    ELSE 'HEALTHY'
  END AS STATUS,
  -- Trust Score: 0-100 composite
  GREATEST(0, LEAST(100,
    100
    - COALESCE(MAX(CASE WHEN METRIC_NAME = 'NULL_COUNT' THEN VALUE END), 0) * 0.1
    - COALESCE(MAX(CASE WHEN METRIC_NAME = 'DUPLICATE_COUNT' THEN VALUE END), 0) * 0.5
    - CASE WHEN COALESCE(MAX(CASE WHEN METRIC_NAME = 'FRESHNESS_HOURS' THEN VALUE END), 0) > 48 THEN 10 ELSE 0 END
  )) AS TRUST_SCORE
FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
WHERE TABLE_DATABASE = 'ON_GOVERNANCE_RFS'
  AND MEASUREMENT_TIME > DATEADD(day, -7, CURRENT_TIMESTAMP())
GROUP BY TABLE_SCHEMA, TABLE_NAME
ORDER BY TABLE_SCHEMA, TABLE_NAME;
