-- ============================================================
-- 08: Cortex Search Service (Semantic Search)
-- ============================================================
USE DATABASE ON_GOVERNANCE_RFS;
USE SCHEMA PUBLIC;

-- ============================================================
-- POPULATE BUSINESS GLOSSARY (search corpus)
-- ============================================================
-- This aggregates column comments + table metadata into a searchable corpus

INSERT INTO BUSINESS_GLOSSARY (
  SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, BUSINESS_DEFINITION,
  DATA_TYPE, DOMAIN, CERTIFICATION, SENSITIVITY, AI_READY,
  DATA_OWNER, DATA_STEWARD, TAGS, TABLE_DESCRIPTION
)
SELECT
  c.TABLE_SCHEMA,
  c.TABLE_NAME,
  c.COLUMN_NAME,
  c.COMMENT AS BUSINESS_DEFINITION,
  c.DATA_TYPE,
  c.TABLE_SCHEMA AS DOMAIN,
  COALESCE(SYSTEM$GET_TAG('ON_GOVERNANCE_RFS.PUBLIC.CERTIFICATION', c.TABLE_SCHEMA || '.' || c.TABLE_NAME, 'TABLE'), 'Draft') AS CERTIFICATION,
  COALESCE(SYSTEM$GET_TAG('ON_GOVERNANCE_RFS.PUBLIC.SENSITIVITY', c.TABLE_SCHEMA || '.' || c.TABLE_NAME, 'TABLE'), 'PUBLIC') AS SENSITIVITY,
  COALESCE(SYSTEM$GET_TAG('ON_GOVERNANCE_RFS.PUBLIC.AI_READY', c.TABLE_SCHEMA || '.' || c.TABLE_NAME, 'TABLE'), 'FALSE') AS AI_READY,
  COALESCE(SYSTEM$GET_TAG('ON_GOVERNANCE_RFS.PUBLIC.DATA_OWNER', c.TABLE_SCHEMA || '.' || c.TABLE_NAME, 'TABLE'), '') AS DATA_OWNER,
  COALESCE(SYSTEM$GET_TAG('ON_GOVERNANCE_RFS.PUBLIC.DATA_STEWARD', c.TABLE_SCHEMA || '.' || c.TABLE_NAME, 'TABLE'), '') AS DATA_STEWARD,
  '' AS TAGS,
  t.COMMENT AS TABLE_DESCRIPTION
FROM INFORMATION_SCHEMA.COLUMNS c
JOIN INFORMATION_SCHEMA.TABLES t
  ON c.TABLE_SCHEMA = t.TABLE_SCHEMA AND c.TABLE_NAME = t.TABLE_NAME
WHERE c.TABLE_SCHEMA NOT IN ('PUBLIC', 'INFORMATION_SCHEMA')
  AND c.COMMENT IS NOT NULL
ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME, c.ORDINAL_POSITION;

-- ============================================================
-- CORTEX SEARCH SERVICE
-- ============================================================
CREATE OR REPLACE CORTEX SEARCH SERVICE MARKETPLACE_SEARCH
  ON BUSINESS_DEFINITION
  ATTRIBUTES SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, DOMAIN, CERTIFICATION, SENSITIVITY, AI_READY, DATA_OWNER, TABLE_DESCRIPTION
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 hour'
  AS (
    SELECT
      GLOSSARY_ID,
      SCHEMA_NAME,
      TABLE_NAME,
      COLUMN_NAME,
      BUSINESS_DEFINITION,
      DOMAIN,
      CERTIFICATION,
      SENSITIVITY,
      AI_READY,
      DATA_OWNER,
      DATA_STEWARD,
      TABLE_DESCRIPTION
    FROM BUSINESS_GLOSSARY
  );
